
cargo-features = ["edition2024","test-dummy-unstable"]
[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]

nalgebra = "0.33.1"
gl = "0.14.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
serenity = "0.12.2"
time = "0.3.36"
poise = "0.6.1"